#!/usr/bin/env python3

from PIL import Image, ImageOps
import random
from fire import *

# Set the width and height of each quarter (The image is always square)
dim = 10


def quarter(dimension, colour) -> Image:
    # Initialize empty image
    one_quarter = Image.new("RGB", (dimension, dimension))

    # Loop over every pixel and set it to one of two colours
    for i in range(dimension):
        for j in range(dimension):
            # Each pixel has a 1/3rd chance of being coloured
            is_coloured = random.randint(0, 2)
            if is_coloured == 1:
                one_quarter.putpixel((i, j), colour)
            else:
                # Set the non-coloured pixels to white
                one_quarter.putpixel((i, j), (255, 255, 255))
    return one_quarter


def generate_multiply_stitch_save(dim: int = 10, name: str = "output"):
    colour = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

    # Initialize the full image
    full_dim = dim * 2
    full_pfp = Image.new("RGB", (full_dim, full_dim))

    # Generate the 4 quarters by flipping and mirroring the first one
    top_left = quarter(dim, colour)
    top_right = ImageOps.mirror(top_left)
    bottom_left = ImageOps.flip(top_left)
    bottom_right = ImageOps.mirror(ImageOps.flip(top_left))

    # Stitch the 4 images together
    full_pfp.paste(top_left, (0, 0))
    full_pfp.paste(top_right, (dim, 0))
    full_pfp.paste(bottom_left, (0, dim))
    full_pfp.paste(bottom_right, (dim, dim))

    # Make sure we end in the right file extension
    if name[4:] != ".png":
        name += ".png"
    full_pfp.save(name)


if __name__ == "__main__":
    command_index = {
        "generate": generate_multiply_stitch_save,
        "g": generate_multiply_stitch_save,
        "gen": generate_multiply_stitch_save
    }
    Fire(command_index)
